#!/usr/bin/env perl
use Mojolicious::Lite;

use DBIx::Sunny;
app->attr(dbh => sub { DBIx::Sunny->connect('dbi:mysql:dbname=bbs', 'root','') });

# Documentation browser under "/perldoc"
#plugin 'PODRenderer';

get '/' => sub {
  my $c = shift;
  my $entries = app->dbh->select_all('SELECT * FROM entry order by created_at desc');

  use Data::Dumper;
  warn Dumper $entries;
 
  $c->stash(entries => $entries);
  $c->render(template => 'index');
};

post '/post' => sub {
  my $c = shift;
  my $entry = $c->param('body');
  app->dbh->query('INSERT INTO entry (body) VALUES (?)', [$entry]);
  $c->redirect_to('/');
};

app->start;
__DATA__

@@ index.html.ep
% layout 'default';
% title '入力フォーム';
%= form_for '/post' => method => 'POST' => begin
  %= text_field 'body'
  %= submit_button '投稿する'
% end
% for my $entry (@$entries) {
    <p><%= $entry->{body} %></p>
% }

@@ layouts/default.html.ep
<!DOCTYPE html>
<html>
  <head><title><%= title %></title></head>
  <body><%= content %></body>
</html>




